### ISSUE TITLE
Logging set to 11 for Icom radios

### ISSUE THREAD

**Issue by AndyTaylorTweet** [g4klx/DStarRepeater#7]
Jonathan, would you consider turning the logging back down for Icom radios;
Commits 6860a9f and a90479a (Sep 10th 2018) add lots of extra logging, or perhaps add a -debug switch that adds all the extra logging?

**Comment by g4klx** [comment]
Done and committed. It's not switchable.

**Comment by AndyTaylorTweet** [comment]
Confirmed this is looking good - can you take a look at the same for Common/DVMegaController.cpp also, there is a load of debug related logs still on here too.

**Comment by g4klx** [comment]
A bit belated, but I've reduced the logging in the DVMega driver now.

**Comment by AndyTaylorTweet** [comment]
Thank you :)
